Release process: publish test UDFs for both previous stable version and (if any) the last alpha/beta/RC when releasing a major version
Refs: tails/tails#18960

diff --git a/bin/publish-test-udfs b/bin/publish-test-udfs
--- a/bin/publish-test-udfs
+++ b/bin/publish-test-udfs
@@ -8,15 +8,31 @@ git fetch
 git switch master
 git merge origin/master
 
-release_udf="wiki/src/upgrade/v2/Tails/${PREVIOUS_STABLE_VERSION:?}/amd64/${DIST:?}/upgrades.yml"
-test_udf="wiki/src/upgrade/v2/Tails/${PREVIOUS_STABLE_VERSION:?}/amd64/test/upgrades.yml"
+# We always provide an upgrade path from the last stable version
+previous_versions="${PREVIOUS_STABLE_VERSION:?}"
+# ... but also from the last of any alphas/betas/RCs. Given Tails
+# versioning scheme we trivially have that that can only be
+# $PREVIOUS_VERSION, but only if it isn't the same as the previous
+# stable release (alpha/beta/RC is not stable by definition).
+if [ "${PREVIOUS_STABLE_VERSION}" != "${PREVIOUS_VERSION}" ]; then
+    previous_versions="${previous_versions} ${PREVIOUS_VERSION:?}"
+fi
 
-mkdir -p "$(dirname "$test_udf")"
-git show "origin/${WEBSITE_RELEASE_BRANCH:?}:${release_udf:?}" \
-    | sed -e "s/channel: ${DIST:?}/channel: test/" > "${test_udf:?}"
-echo "Signing ${test_udf:?}"
-gpg -u "${TAILS_SIGNATURE_KEY:?}" --armor --detach-sign "${test_udf:?}"
-mv "${test_udf:?}".asc "${test_udf:?}".pgp
-git add "${test_udf:?}"*
+for version in ${previous_versions}; do
+    release_udf="wiki/src/upgrade/v2/Tails/${version}/amd64/${DIST:?}/upgrades.yml"
+    if [ ! -e "${release_udf}" ]; then
+        echo "Cannot find: ${release_udf}" >&2
+        exit 1
+    fi
+    test_udf="wiki/src/upgrade/v2/Tails/${version}/amd64/test/upgrades.yml"
+
+    mkdir -p "$(dirname "$test_udf")"
+    git show "origin/${WEBSITE_RELEASE_BRANCH:?}:${release_udf:?}" \
+        | sed -e "s/channel: ${DIST:?}/channel: test/" > "${test_udf:?}"
+    echo "Signing ${test_udf:?}"
+    gpg -u "${TAILS_SIGNATURE_KEY:?}" --armor --detach-sign "${test_udf:?}"
+    mv "${test_udf:?}".asc "${test_udf:?}".pgp
+    git add "${test_udf:?}"*
+done
 git commit -m "Add incremental upgrades on the test channel for Tails ${VERSION:?}"
 git push origin master:master
